name: "Hello Actions"
description: "Greet someone"
authour: "Has"

inputs: 
  MY_NAME:
    description:"Who to Greet"
    required:true
    default:"World"
    
runs:
  using:"docker"
  image:"DockerFile"
  
branding:
  icon:"mic"
  color:"purple"
